### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by adamrothman** [aio-libs/aiobotocore#573]
## Issue

Commit 42dbd833187ff396e4b0e443eaa5fd0d20b84b66 appears to have broken pagination. The reproducer below works fine using aiobotocore 0.6.0 (with aiohttp 3.0.9), but breaks with aiobotocore 0.7.0 (with aiohttp 3.1.3).

```python
from pprint import pprint

import aiobotocore


async def main():
    session = aiobotocore.get_session()

    async with session.create_client('s3') as s3:
        paginator = s3.get_paginator('list_objects')
        async for page in paginator.paginate(Bucket='some-bucket'):
            for item in page.get('Contents', []):
                pprint(item)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

And the resulting traceback:

```
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "test.py", line 42, in main
    for item in page.get('Contents', []):
AttributeError: 'coroutine' object has no attribute 'get'
sys:1: RuntimeWarning: coroutine 'AioPageIterator.next_page' was never awaited
```

## Root cause

The problem is in `AioPageIterator`'s `__anext__`:
https://github.com/aio-libs/aiobotocore/blob/42fc4d9765d84b8d16168b750296859b85ac698e/aiobotocore/paginate.py#L93-L97

Rather than awaiting `self.next_page()`, the coroutine is being returned directly. This is definitely wrong; changing the last line to `return await self.next_page()` fixes the issue (I'll submit a PR).

What I don't understand is how it was working before, and why simply switching from using the `@asyncio.coroutine` decorator to native `async def` functions exposed it.

**Comment by thehesiod** [comment]
mind adding a new / updating the existing testcase to ensure it doesn't happen again?

**Comment by thehesiod** [comment]
btw updated your example, you don't need to call s3.close because you're using `async with`

**Comment by thehesiod** [comment]
hmm, how is this passing: https://github.com/aio-libs/aiobotocore/blob/master/tests/test_basic_s3.py#L111

**Comment by thehesiod** [comment]
figured out why we didn't catch these, looks like the tests were disabled.  Working on a PR to fix them

**Comment by thehesiod** [comment]
@adamrothman after a deep dive down the rabbit hole I've created https://github.com/aio-libs/aiobotocore/pull/576 to enable a lot more tests to run via moto, and to do this I needed to pull in your change.  Is it ok to continue this in that PR and close this one?

**Comment by thehesiod** [comment]
or you can pull that into your PR, either way

**Comment by adamrothman** [comment]
@thehesiod absolutely, closing this and I’ll follow along on #576. Thanks!

**Comment by adamrothman** [comment]
Oops, meant to close my PR, not the issue.
